"ГАЙД ПО МОДДИНГУ / MODDING GUIDE"
const modded = false
"ВКЛЮЧИТЕ ПЕРЕМЕННУЮ ВЫШЕ ЕСЛИ ХОТИТЕ СДЕЛАТЬ МОД"
"ENABLE THIS VARIABLE IF YOU WANNA MAKE A MOD"

const can_vanilla = false
"ВСТАВЬТЕ ТУТ TRUE ЕСЛИ ПРОЕКТ ИЗ ВАШЕГО МОДА МОЖНО ЗАПУСКАТЬ В ОФФИЦИАЛЬНОЙ ВЕРСИИ"
"IF YOUR MOD`S RROJECT CAN RUN IN VANILLA ENABLE THIS"

const mod_name = "NAME_HERE" 
"ВВЕДИТЕ ИМЯ МОДА ЗДЕСЬ"
"MOD NAME HERE"

"RUSSIAN / "
"РАЗДЕЛЫ"
"	1 свои модули"
"		шаг 1 - создание в выборе модулей ( КОРЕНЬ > ModlKat > ScrollContainer > VBoxContainer > ( любой контейнер ) > Модуль ), скопируйте его"
"		шаг 2 - придумайте ему название и переименуйте Node ( Узел )"
"		шаг 3 - можете менять внутренности как хотите"
"		шаг 4 - создание самого модуля ( КОРЕНЬ > Holders > Модуль ) копируйте и называйте его так-же как и в выборе модулей"
"		шаг 5 - меняйте внутренности как хотите"
"		шаг 6 - добавьте в game.gd в функцию vling обработчик модуля"
"		ГОТОВО!"
"	2 свои блоки"
"		шаг 1 - идите в ( КОРЕНЬ > Katalog > Blocks > ( Нужная вам категория ) > Блок ) скопируйте его"
"		шаг 2 - переименуйте блок как вам угодно"
"		шаг 3 - меняйте внутренности как хотите"
"		шаг 4 - добавьте в game.gd в функцию _compilyarka обработчик блока"
"		шаг 5 - добавьте в game.gd в функцию obr то что будет делать ваш блок"
"	3 формулы"
"		мне лень делать гайд на формулы аповыащщвыащговаыщыащг"
"	( ВСЕ ОСТАЛЬНОЕ ПРОСТО , ДУМАЮ САМИ РАЗБЕРЕТЕСЬ )"

"ENGLISH / "
"THEMES"
"	1 your own module-formules"
"		step 1 - create it in module select ( SCENE > ModlKat > ScrollContainer > VBoxContainer > ( any container ) > Module ), just copy it"
"		step 2 - rename the module Node"
"		step 3 - you can change the insides as you wish"
"		step 4 - create module ( SCENE > Holders > Module ) copy it and name it the same as the previous one"
"		step 5 - you can change the insides as you wish"
"		step 6 - add in game.gd inside func vling module handler"
"		DONE!"
"	2 your own blocks"
"		step 1 - go to ( SCENE > Katalog > Blocks > Category > Block ) copy it"
"		step 2 - rename it"
"		step 3 - you can change the insides as you wish"
"		step 4 - add in game.gd inside func _compilyarka block handler"
"		step 5 - add in game.gd inside func obr what it will do"
"	3 formules"
"		step 1 - Idk lol"
